---
- name: install Windows based unarchive module OS pkgs...
  become: '{{ unarchivedeps_privilege_escalation }}'
  become_user: '{{ unarchivedeps_privilege_escalation_user }}'
  when: ansible_os_family == "Windows"
  loop: "{{ unarchivedeps_win_modules }}"
  win_psmodule:
    name: "{{ item }}"
    allow_clobber: true
    state: present
